export type DeterminantKey =
	"social cohesion and involvement"
	| "social mixity, equity and solidarity"
	| "neighbourhood socio-economic status"
	| "population economic activity and security"
	| "active transportation choice"
	| "relaxing, cultural and recreational activities"
	| "healthy food knowledge and choice"
	| "sport and physical activities"
	| "sun light access and visual indoor comfort"
	| "indoor air quality and hygrothermal comfort"
	| "acoustic indoor comfort"
	| "stability and regularity of access to quality housing"
	| "neighbourhood functional mix"
	| "access to a diversified and qualitative offer"
	| "urban concentration and urbanization level"
	| "multi-sensory outdoor comfort and diversity"
	| "interactions with natural environments"
	| "aeraulic and hygrothermal outdoor comfort"
	| "sun light exposure and visual outdoor comfort"
	| "urban appropriation access and equity"
	| "spatial legibility and security feeling"
	| "road network quality for active transportation"
	| "access to and variety of the transportation offer"
	| "environment and biodiversity preservation"
	| "prevention and resilience to environmental hazards"
	| "environment and biodiversity awareness"
	| "air pollution and electromagnetic fields low exposure"
	| "industrial, water and soil pollution low exposure"
	| "road traffic low exposure"
	| "qualitative and adequate sound environment";