export const pictures = [{
	"context": "villeurbanne",
	"determinant": "social cohesion and involvement",
	"filename": "DSC04885.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social cohesion and involvement",
	"filename": "DSC05043.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social cohesion and involvement",
	"filename": "DSC05065.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social cohesion and involvement",
	"filename": "DSC05110.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social cohesion and involvement",
	"filename": "DSC05174.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social cohesion and involvement",
	"filename": "DSC05186.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social cohesion and involvement",
	"filename": "LYO_056850.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - Richard P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social mixity, equity and solidarity",
	"filename": "DSC04909.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social mixity, equity and solidarity",
	"filename": "LYO_056908.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - Richard P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social mixity, equity and solidarity",
	"filename": "DSC04968.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "social mixity, equity and solidarity",
	"filename": "LYO_041894.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "population economic activity and security",
	"filename": "LYO_059537.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  MOMMEJA M.",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "population economic activity and security",
	"filename": "DSC05160.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "population economic activity and security",
	"filename": "DSC05162.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "population economic activity and security",
	"filename": "DSC05168.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "neighbourhood socio-economic status",
	"filename": "LYO_057022.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD.P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "neighbourhood socio-economic status",
	"filename": "dic_1012phot_025.JPG",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Julien RAMBAUD - Alpaca Productions",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "active transportation choice",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_cycles.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "R\u00e9seau de voies et pistes cyclables",
}, {
	"context": "villeurbanne",
	"determinant": "active transportation choice",
	"filename": "LYO_059384.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  ROUSSEAU T.",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "active transportation choice",
	"filename": "DSC04957.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "active transportation choice",
	"filename": "DSC04949.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "sport and physical activities",
	"filename": "LYO_056717.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD.P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "sport and physical activities",
	"filename": "DSC05238.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "sport and physical activities",
	"filename": "DSC05047.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "sport and physical activities",
	"filename": "DSC05079.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "sport and physical activities",
	"filename": "DSC05214.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "sport and physical activities",
	"filename": "DSC05027.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "sport and physical activities",
	"filename": "LYO_055853.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "healthy food knowledge and choice",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_alimentation.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux march\u00e9s alimentaires dans un rayon d'1km",
}, {
	"context": "villeurbanne",
	"determinant": "healthy food knowledge and choice",
	"filename": "DSC04867.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "healthy food knowledge and choice",
	"filename": "DSC04868.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "DSC05155.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "LYO_057019.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD.P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "LYO_056688.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD.P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "LYO_056781.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD.P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "LYO_045859.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  GUINET B",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC05116.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC05142.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_medecins.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Densit\u00e9 de m\u00e9decins g\u00e9n\u00e9ralistes selon un maillage de 300x300m",
}, {
	"context": "villeurbanne",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_sport.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux \u00e9quipements sportifs dans un rayon de 500 m",
}, {
	"context": "villeurbanne",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "LYO_051188.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "DSC05169.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "LYO_056751.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD.P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "LYO_056684.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD.P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "DSC05177.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "DSC05225.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "neighbourhood functional mix",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_scolaires.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux \u00e9tablissements scolaires  dans un rayon de 300 m",
}, {
	"context": "villeurbanne",
	"determinant": "neighbourhood functional mix",
	"filename": "LYO_056905.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD.P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "neighbourhood functional mix",
	"filename": "dic_1692phot_034.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "DSC05017.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "LYO_055834.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "DSC05036.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "DSC05058.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "DSC05200.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "LYO_045313.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  GUINET B",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "LYO_057009.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "aeraulic and hygrothermal outdoor comfort",
	"filename": "LYO_056725.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "sun light exposure and visual outdoor comfort",
	"filename": "DSC05221.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "interactions with natural environments",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_espaces_verts.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Parcs, jardins et espaces verts publics",
}, {
	"context": "villeurbanne",
	"determinant": "interactions with natural environments",
	"filename": "DSC05247.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "interactions with natural environments",
	"filename": "DSC05294.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "interactions with natural environments",
	"filename": "LYO_045855.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - GUINET B",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "aeraulic and hygrothermal outdoor comfort",
	"filename": "dic_1692phot_006.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "interactions with natural environments",
	"filename": "dic_2152phot_020.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "urban appropriation access and equity",
	"filename": "DSC05194.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "urban appropriation access and equity",
	"filename": "DSC05215.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "urban appropriation access and equity",
	"filename": "LYO_055854.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "spatial legibility and security feeling",
	"filename": "DSC04924.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "spatial legibility and security feeling",
	"filename": "dic_1692phot_002.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "road network quality for active transportation",
	"filename": "DSC04996.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "road network quality for active transportation",
	"filename": "DSC05098.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "road network quality for active transportation",
	"filename": "LYO_056704.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to and variety of the transportation offer",
	"filename": "LYO_056831.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to and variety of the transportation offer",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_bus.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Lignes et stations de bus",
}, {
	"context": "villeurbanne",
	"determinant": "access to and variety of the transportation offer",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_Tram.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux stations de tramway dans un rayon de 500m",
}, {
	"context": "villeurbanne",
	"determinant": "access to and variety of the transportation offer",
	"filename": "DSC05003.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to and variety of the transportation offer",
	"filename": "dic_0563phot_017.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "access to and variety of the transportation offer",
	"filename": "dic_0614phot_016.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "road network quality for active transportation",
	"filename": "dic_0959phot_013.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "road network quality for active transportation",
	"filename": "dic_2082phot_007.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Ana\u00efs MERCEY",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity preservation",
	"filename": "LYO_045855.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - GUINET B",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity preservation",
	"filename": "LYO_059789.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  MOMMEJA M.",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity preservation",
	"filename": "LYO_056725.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity preservation",
	"filename": "LYO_056726.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC05070.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC05259.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC05277.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC05279.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "prevention and resilience to environmental hazards",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_vulnerabilites.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Vuln\u00e9rabilit\u00e9 \u00e0 la surchauffe urbaine diurne",
}, {
	"context": "villeurbanne",
	"determinant": "prevention and resilience to environmental hazards",
	"filename": "DSC05014.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity awareness",
	"filename": "DSC05122.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity awareness",
	"filename": "dic_1181phot_006.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "environment and biodiversity awareness",
	"filename": "dic_1340phot_043.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "air pollution and electromagnetic fields low exposure",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_pollution_air.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Concentration en dioxyde d'azote dans l'air en moyenne annuelle (en \u00b5g\/m\u00b3)",
}, {
	"context": "villeurbanne",
	"determinant": "air pollution and electromagnetic fields low exposure",
	"filename": "DSC05067.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "qualitative and adequate sound environment",
	"filename": "DSC04937.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "qualitative and adequate sound environment",
	"filename": "DSC04964.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "qualitative and adequate sound environment",
	"filename": "ExpoLyon_Carto_diagramme_001_Charpennes_nuisances_sonores.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Niveau sonore moyen sur une journ\u00e9e (en dB (A))",
}, {
	"context": "villeurbanne",
	"determinant": "qualitative and adequate sound environment",
	"filename": "DSC04960.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "qualitative and adequate sound environment",
	"filename": "DSC04970.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "qualitative and adequate sound environment",
	"filename": "DSC04972.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "qualitative and adequate sound environment",
	"filename": "DSC05133.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "LYO_056962.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RICHARD P",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04906.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC05188.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04929.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA - Jacques Merel",
	"title": "",
}, {
	"context": "villeurbanne",
	"determinant": "air pollution and electromagnetic fields low exposure",
	"filename": "dic_1409phot_005.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "social cohesion and involvement",
	"filename": "DSC04565.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "social cohesion and involvement",
	"filename": "DSC04707.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "social cohesion and involvement",
	"filename": "LYO_055903.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - DESAINTJEAN F",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "social cohesion and involvement",
	"filename": "LYO_056086.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "social cohesion and involvement",
	"filename": "LYO_045363.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "social mixity, equity and solidarity",
	"filename": "DSC04636.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "social mixity, equity and solidarity",
	"filename": "DSC04766.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "social mixity, equity and solidarity",
	"filename": "DSC04800.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "population economic activity and security",
	"filename": "DSC04730.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "social cohesion and involvement",
	"filename": "dic_0966phot_016.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "active transportation choice",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluence_cycles.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "R\u00e9seau de voies et pistes cyclables",
}, {
	"context": "lyon-2",
	"determinant": "active transportation choice",
	"filename": "DSC04513.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "active transportation choice",
	"filename": "DSC04590.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "active transportation choice",
	"filename": "DSC04603.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "active transportation choice",
	"filename": "DSC04605.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "active transportation choice",
	"filename": "DSC04614.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "active transportation choice",
	"filename": "DSC04642.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "active transportation choice",
	"filename": "DSC04709.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "active transportation choice",
	"filename": "DSC04728.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sport and physical activities",
	"filename": "LYO_045360.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sport and physical activities",
	"filename": "DSC04675.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sport and physical activities",
	"filename": "DSC04760.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sport and physical activities",
	"filename": "DSC04774.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "healthy food knowledge and choice",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluence_alimentation.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux march\u00e9s alimentaires dans un rayon d'1km",
}, {
	"context": "lyon-2",
	"determinant": "healthy food knowledge and choice",
	"filename": "LYO_025253.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon\u00a9 PressWeb - GALLICE B",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "healthy food knowledge and choice",
	"filename": "LYO_055907.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - DESAINTJEAN F",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "healthy food knowledge and choice",
	"filename": "DSC04806.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "healthy food knowledge and choice",
	"filename": "DSC04816.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "LYO_048726.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "LYO_045619.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "P0733_002_00361.jpg",
	"priority": 0,
	"source": "\u00a9 Biblioth\u00e8que municipale de Lyon - Blanchoz-Rh\u00f4ne, Sylviane",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "DSC04632.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sport and physical activities",
	"filename": "dic_0757phot_014.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sport and physical activities",
	"filename": "dic_1827phot_067.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "dic_2118phot_010.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Hugo RIBES - Item",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "dic_2118phot_023.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Hugo RIBES - Item",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sport and physical activities",
	"filename": "dic_0889phot_085.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "dic_1012phot_081.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Julien RAMBAUD - Alpaca Productions",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sport and physical activities",
	"filename": "dic_1007phot_047.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Julien RAMBAUD - Alpaca Productions",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04619.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04626.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04628.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04641.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04722.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "indoor air quality and hygrothermal comfort",
	"filename": "DSC04617.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sun light access and visual indoor comfort",
	"filename": "DSC04751.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sun light access and visual indoor comfort",
	"filename": "dic_1074phot_021.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sun light access and visual indoor comfort",
	"filename": "dic_1296phot_060.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "sun light access and visual indoor comfort",
	"filename": "dic_1296phot_069.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluence_medecins.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Densit\u00e9 de m\u00e9decins g\u00e9n\u00e9ralistes selon un maillage de 300x300m",
}, {
	"context": "lyon-2",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluence_sport.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux \u00e9quipements sportifs dans un rayon de 500 m",
}, {
	"context": "lyon-2",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "P0757_007_02213.jpg",
	"priority": 0,
	"source": "\u00a9 Biblioth\u00e8que municipale de Lyon - Cusin, Antoine",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "DSC04500.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "DSC04668.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluence_scolaires.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux \u00e9tablissements scolaires  dans un rayon de 300 m",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "DSC04814.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "DSC04798.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "P0762_005_00005.jpg",
	"priority": 0,
	"source": "\u00a9 Biblioth\u00e8que municipale de Lyon - Meyer, Anne",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "P0799_009_00006.jpg",
	"priority": 0,
	"source": "\u00a9 Biblioth\u00e8que municipale de Lyon - Bouillaud, Nathalie",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "dic_1501phot_033.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "dic_2134phot_038.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Ana\u00efs MERCEY",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "dic_1074phot_002.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "dic_1074phot_012.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "neighbourhood functional mix",
	"filename": "dic_2134phot_037.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Ana\u00efs MERCEY",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "LYO_050213.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "DSC04578.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "DSC04601.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "DSC04830.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "DSC04700.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "aeraulic and hygrothermal outdoor comfort",
	"filename": "LYO_045488.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - GILLET D",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "aeraulic and hygrothermal outdoor comfort",
	"filename": "P0799_009_00006.jpg",
	"priority": 0,
	"source": "\u00a9 Biblioth\u00e8que municipale de Lyon - Bouillaud, Nathalie",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "aeraulic and hygrothermal outdoor comfort",
	"filename": "DSC04657.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "interactions with natural environments",
	"filename": "DSC04609.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "interactions with natural environments",
	"filename": "dic_0757phot_017.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "dic_0757phot_027.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "dic_0889phot_082.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "dic_0889phot_092.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "interactions with natural environments",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluence_espaces_verts.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Parcs, jardins et espaces verts publics",
}, {
	"context": "lyon-2",
	"determinant": "interactions with natural environments",
	"filename": "dic_2134phot_029.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Ana\u00efs MERCEY",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "interactions with natural environments",
	"filename": "dic_2180phot_016.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Ana\u00efs MERCEY",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "dic_0711phot_094.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "interactions with natural environments",
	"filename": "dic_0757phot_024.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "urban appropriation access and equity",
	"filename": "DSC04650.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "urban appropriation access and equity",
	"filename": "DSC04662.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "spatial legibility and security feeling",
	"filename": "DSC04843.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "spatial legibility and security feeling",
	"filename": "DSC04838.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "spatial legibility and security feeling",
	"filename": "DSC04545.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "spatial legibility and security feeling",
	"filename": "DSC04839.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "urban appropriation access and equity",
	"filename": "dic_0757phot_023.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "DSC04505.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "LYO_050214.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "DSC04526.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "DSC04531.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "DSC04536.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "DSC04556.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "DSC04688.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluence_Tram.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux stations de tramway dans un rayon de 500m",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluence_bus.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Lignes et stations de bus",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "DSC04819.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "LYO_049896.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "DSC04848.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "DSC04831.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "DSC04683.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "dic_0757phot_018.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "dic_0889phot_091.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "dic_0889phot_090.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "dic_1323phot_008.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road network quality for active transportation",
	"filename": "dic_1323phot_007.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "dic_0821phot_005.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "dic_1226phot_005.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Lucie SAINTVOIRIN",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "access to and variety of the transportation offer",
	"filename": "dic_1273phot_015.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity preservation",
	"filename": "LYO_048730.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC04747.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC04736.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC04577.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity preservation",
	"filename": "P0905_001_00003.jpg",
	"priority": 0,
	"source": "\u00a9 Biblioth\u00e8que municipale de Lyon - Michel, Pierre",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity preservation",
	"filename": "LYO_055907.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - DESAINTJEAN F",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "prevention and resilience to environmental hazards",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluences_vulnerabilites.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Vuln\u00e9rabilit\u00e9 \u00e0 la surchauffe urbaine diurne",
}, {
	"context": "lyon-2",
	"determinant": "prevention and resilience to environmental hazards",
	"filename": "DSC04732.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity awareness",
	"filename": "DSC04771.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity awareness",
	"filename": "DSC04761.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity awareness",
	"filename": "dic_0757phot_021.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "environment and biodiversity awareness",
	"filename": "dic_2180phot_008.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Ana\u00efs MERCEY",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "air pollution and electromagnetic fields low exposure",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluence_pollution_air.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Concentration en dioxyde d'azote dans l'air en moyenne annuelle (en \u00b5g\/m\u00b3)",
}, {
	"context": "lyon-2",
	"determinant": "air pollution and electromagnetic fields low exposure",
	"filename": "LYO_050219.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "qualitative and adequate sound environment",
	"filename": "DSC04504.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04574.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04846.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "LYO_047356.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road traffic low exposure",
	"filename": "LYO_048737.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "road traffic low exposure",
	"filename": "DSC04505.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "qualitative and adequate sound environment",
	"filename": "ExpoLyon_Carto_diagramme_002_Confluences_nuisances_sonores.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Niveau sonore moyen sur une journ\u00e9e (en dB (A))",
}, {
	"context": "lyon-2",
	"determinant": "qualitative and adequate sound environment",
	"filename": "dic_1609phot_020.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Ana\u00efs MERCEY",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "qualitative and adequate sound environment",
	"filename": "dic_1074phot_025.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "lyon-2",
	"determinant": "air pollution and electromagnetic fields low exposure",
	"filename": "dic_1235phot_014.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "social cohesion and involvement",
	"filename": "LYO_058733.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "social cohesion and involvement",
	"filename": "DSC04403.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "social cohesion and involvement",
	"filename": "DSC04418.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "social mixity, equity and solidarity",
	"filename": "LYO_057206.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - RICHARD P",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "social mixity, equity and solidarity",
	"filename": "DSC04475.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "social mixity, equity and solidarity",
	"filename": "DSC04428.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "social mixity, equity and solidarity",
	"filename": "DSC04419.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "social mixity, equity and solidarity",
	"filename": "DSC04272.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "neighbourhood socio-economic status",
	"filename": "LYO_058731.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "neighbourhood socio-economic status",
	"filename": "DSC04258.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "neighbourhood socio-economic status",
	"filename": "DSC04322.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "neighbourhood socio-economic status",
	"filename": "DSC04323.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "neighbourhood socio-economic status",
	"filename": "DSC04354.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "neighbourhood socio-economic status",
	"filename": "DSC04326.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "active transportation choice",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_cycles.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "R\u00e9seau de voies et pistes cyclables",
}, {
	"context": "la-saulaie",
	"determinant": "active transportation choice",
	"filename": "DSC04133.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "active transportation choice",
	"filename": "_MG_5469.jpg",
	"priority": 0,
	"source": "\u00a9 CAUE Rh\u00f4ne M\u00e9tropole \/ Florent Perroud",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "active transportation choice",
	"filename": "DSC04361.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "active transportation choice",
	"filename": "DSC04364.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "sport and physical activities",
	"filename": "DSC04284.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "healthy food knowledge and choice",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_alimentation.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux march\u00e9s alimentaires dans un rayon d'1km",
}, {
	"context": "la-saulaie",
	"determinant": "healthy food knowledge and choice",
	"filename": "DSC04127.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "healthy food knowledge and choice",
	"filename": "DSC04374.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "healthy food knowledge and choice",
	"filename": "DSC04433.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "DSC04357.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "DSC04450.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "relaxing, cultural and recreational activities",
	"filename": "DSC04390.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04226.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "_MG_6807.jpg",
	"priority": 0,
	"source": "\u00a9 CAUE Rh\u00f4ne M\u00e9tropole \/ Florent Perroud",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04329.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04433.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04428.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04100.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "DSC04270.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "stability and regularity of access to quality housing",
	"filename": "dic_1831phot_035.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_medecins.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Densit\u00e9 de m\u00e9decins g\u00e9n\u00e9ralistes selon un maillage de 300x300m",
}, {
	"context": "la-saulaie",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_sport.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux \u00e9quipements sportifs dans un rayon de 500 m",
}, {
	"context": "la-saulaie",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "DSC04486.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "access to a diversified and qualitative offer",
	"filename": "DSC04494.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "neighbourhood functional mix",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_scolaires.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux \u00e9tablissements scolaires  dans un rayon de 300 m",
}, {
	"context": "la-saulaie",
	"determinant": "neighbourhood functional mix",
	"filename": "DSC04497.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "neighbourhood functional mix",
	"filename": "dic_0390phot_001.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "LYO_043897.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - BLANQUET O",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "LYO_047151.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - GUINET B",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "multi-sensory outdoor comfort and diversity",
	"filename": "DSC04294.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "aeraulic and hygrothermal outdoor comfort",
	"filename": "LYO_047149.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon - GUINET B",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "aeraulic and hygrothermal outdoor comfort",
	"filename": "DSC04337.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "aeraulic and hygrothermal outdoor comfort",
	"filename": "DSC04413.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "sun light exposure and visual outdoor comfort",
	"filename": "DSC04435.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "interactions with natural environments",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_espaces_verts.jpg",
	"priority": 0,
	"source": "\u00a9 AIA Life Designers",
	"title": "Parcs, jardins et espaces verts publics",
}, {
	"context": "la-saulaie",
	"determinant": "interactions with natural environments",
	"filename": "LYO_058759.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "interactions with natural environments",
	"filename": "_MG_6807.jpg",
	"priority": 0,
	"source": "\u00a9 CAUE Rh\u00f4ne M\u00e9tropole \/ Florent Perroud",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "urban appropriation access and equity",
	"filename": "DSC04423.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "spatial legibility and security feeling",
	"filename": "DSC04476.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "spatial legibility and security feeling",
	"filename": "DSC04176.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "spatial legibility and security feeling",
	"filename": "DSC04384.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "road network quality for active transportation",
	"filename": "DSC04107.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "road network quality for active transportation",
	"filename": "DSC04119.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "access to and variety of the transportation offer",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_Tram.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Accessibilit\u00e9 aux stations de tramway dans un rayon de 500m",
}, {
	"context": "la-saulaie",
	"determinant": "access to and variety of the transportation offer",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_bus.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Lignes et stations de bus",
}, {
	"context": "la-saulaie",
	"determinant": "access to and variety of the transportation offer",
	"filename": "LYO_044862.jpg",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "access to and variety of the transportation offer",
	"filename": "DSC04129.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "access to and variety of the transportation offer",
	"filename": "DSC04134.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "access to and variety of the transportation offer",
	"filename": "LYO_058762.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "access to and variety of the transportation offer",
	"filename": "dic_0614phot_017.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "access to and variety of the transportation offer",
	"filename": "dic_0614phot_018.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "road network quality for active transportation",
	"filename": "dic_0614phot_027.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Laurence DANI\u00c8RE",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity preservation",
	"filename": "_MG_5469.jpg",
	"priority": 0,
	"source": "\u00a9 CAUE Rh\u00f4ne M\u00e9tropole \/ Florent Perroud",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC04170.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC04332.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC04436.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC04190.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC04443.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity preservation",
	"filename": "DSC04469.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "prevention and resilience to environmental hazards",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_vulnerabilites.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Vuln\u00e9rabilit\u00e9 \u00e0 la surchauffe urbaine diurne",
}, {
	"context": "la-saulaie",
	"determinant": "prevention and resilience to environmental hazards",
	"filename": "DSC04479.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity awareness",
	"filename": "DSC04178.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity awareness",
	"filename": "DSC04493.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "environment and biodiversity preservation",
	"filename": "dic_0391phot_019.jpg",
	"priority": 0,
	"source": "\u00a9 M\u00e9tropole de Lyon - Thierry FOURNIER",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "air pollution and electromagnetic fields low exposure",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_pollution_air.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Concentration en dioxyde d'azote dans l'air en moyenne annuelle (en \u00b5g\/m\u00b3)",
}, {
	"context": "la-saulaie",
	"determinant": "qualitative and adequate sound environment",
	"filename": "ExpoLyon_Carto_diagramme_003_Oullins_nuisances_sonores.jpg",
	"priority": 1,
	"source": "\u00a9 AIA Life Designers",
	"title": "Niveau sonore moyen sur une journ\u00e9e (en dB (A))",
}, {
	"context": "la-saulaie",
	"determinant": "qualitative and adequate sound environment",
	"filename": "LYO_058729.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "qualitative and adequate sound environment",
	"filename": "DSC04245.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "qualitative and adequate sound environment",
	"filename": "DSC04249.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "LYO_058730.JPG",
	"priority": 0,
	"source": "\u00a9 UrbaLyon -  RUCH MP",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04212.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04264.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04150.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04315.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04317.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04352.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04389.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04395.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04202.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "industrial, water and soil pollution low exposure",
	"filename": "DSC04226.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "road traffic low exposure",
	"filename": "DSC04451.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "road traffic low exposure",
	"filename": "DSC04453.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "road traffic low exposure",
	"filename": "DSC04453.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "road traffic low exposure",
	"filename": "DSC04206.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}, {
	"context": "la-saulaie",
	"determinant": "road traffic low exposure",
	"filename": "DSC04217.jpg",
	"priority": 0,
	"source": "\u00a9 Fondation AIA \/ Jacques Merel",
	"title": "",
}] as const;
