export const pictures = [
	{
		"context": "lyon-2",
		"determinant": "social cohesion and involvement",
		"determinantFamilyLetter": "A",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_maisondesassos",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_skatteparc",
		"priority": 0,
		"source": "© Alain FISCHER , Ville de Grenoble ",
		"title": "© Alain FISCHER , Ville de Grenoble ",
	},
	{
		"context": "lyon-2",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_grafiti",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_croixrouge",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_maisondesassos",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "neighbourhood socio-economic status",
		"determinantFamilyLetter": "A",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "casernedebonne_commerces",
		"priority": 0,
		"source": "casernedebonne_commerces_A4",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "neighbourhood socio-economic status",
		"determinantFamilyLetter": "A",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "caserndedebonne_universite",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "population economic activity and security",
		"determinantFamilyLetter": "A",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "casernedebonne_commerces",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "active transportation choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_pieton",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_sport",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_escalade",
		"priority": 0,
		"source": "©Auriane Poillet Ville de Grenoble",
		"title": "©Auriane Poillet Ville de Grenoble",
	},
	{
		"context": "lyon-2",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_yoga",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_gymnase",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "casernedebonne_supert",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "relaxing, cultural and recreational activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "casernedebonne_cinema",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "relaxing, cultural and recreational activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "casernedebonne_yoga",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_grafiti",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "casernedebonne_expositionsoleil",
		"priority": 0,
		"source": "© Sylvain Frappat - Ville de Grenobl",
		"title": "© Sylvain Frappat - Ville de Grenobl",
	},
	{
		"context": "lyon-2",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "casernedebonne_espaceexterieurensolleillee",
		"priority": 0,
		"source": "© Sylvain Frappat - Ville de Grenobl",
		"title": "© Sylvain Frappat - Ville de Grenobl",
	},
	{
		"context": "lyon-2",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_gymnase",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_skatteparc",
		"priority": 0,
		"source": "© Alain FISCHER , Ville de Grenoble",
		"title": "© Alain FISCHER , Ville de Grenoble",
	},
	{
		"context": "lyon-2",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_croixrouge",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_supertbio",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_superet",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_ruepietonne",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2021 ",
	},
	{
		"context": "lyon-2",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "caserndebonne_parc",
		"priority": 0,
		"source": "Flickr",
		"title": "© Sylvain Frappat - Ville de Grenobl",
	},
	{
		"context": "lyon-2",
		"determinant": "neighbourhood functional mix",
		"determinantFamilyLetter": "D",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "casernedebonne_superet",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "multi-sensory outdoor comfort and diversity",
		"determinantFamilyLetter": "E",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_laccanard",
		"priority": 0,
		"source": "Flickr",
		"title": "© Alain FISCHER 2022 - Ville de Grenoble",
	},
	{
		"context": "lyon-2",
		"determinant": "aeraulic and hygrothermal outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_chantiernoisy",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "aeraulic and hygrothermal outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_pontaudessusdeleau",
		"priority": 0,
		"source": "© AIA Life Designer",
		"title": "© AIA Life Designer",
	},
	{
		"context": "lyon-2",
		"determinant": "sun light exposure and visual outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "casernedebonne_espaceexterieurensolleillee",
		"priority": 0,
		"source": "© Sylvain Frappat - Ville de Grenobl",
		"title": "© Sylvain Frappat - Ville de Grenobl",
	},
	{
		"context": "lyon-2",
		"determinant": "interactions with natural environments",
		"determinantFamilyLetter": "E",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "casernedebonne_grandespaces",
		"priority": 0,
		"source": "© AIA Life Designer",
		"title": "© AIA Life Designer",
	},
	{
		"context": "lyon-2",
		"determinant": "urban appropriation access and equity",
		"determinantFamilyLetter": "F",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_bancsfacelac",
		"priority": 0,
		"source": "© Alain FISCHER , Ville de Grenoble",
		"title": "© Alain FISCHER , Ville de Grenoble ",
	},
	{
		"context": "lyon-2",
		"determinant": "urban appropriation access and equity",
		"determinantFamilyLetter": "F",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_skatteparc",
		"priority": 0,
		"source": "© Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "lyon-2",
		"determinant": "spatial legibility and security feeling",
		"determinantFamilyLetter": "F",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_grafiti",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_pieton",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_rue",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_commerces",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "access to and variety of the transportation offer",
		"determinantFamilyLetter": "G",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_bus",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "access to and variety of the transportation offer",
		"determinantFamilyLetter": "G",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_croisementbusvelo",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_espacesvertspublics",
		"priority": 0,
		"source": "© Sylvain Frappat - Ville de Grenoble",
		"title": "© Sylvain Frappat - Ville de Grenoble",
	},
	{
		"context": "lyon-2",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_coursdeau",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_pontaudessusdeleau",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "lyon-2",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "casernedebonne_nature",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "prevention and resilience to environmental hazards",
		"determinantFamilyLetter": "H",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_chantiernoisy",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "environment and biodiversity awareness",
		"determinantFamilyLetter": "H",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "casernedebonne_coursdeau",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "qualitative and adequate sound environment",
		"determinantFamilyLetter": "I",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_route",
		"priority": 0,
		"source": "AIA Life designers",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "qualitative and adequate sound environment",
		"determinantFamilyLetter": "I",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "casernedebonne_ruepietonne",
		"priority": 0,
		"source": "AIA Life designers",
		"title": "© Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "road traffic low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "casernedebonne_routes",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© AIA Life Designers-Jacques Merel",
	},
	{
		"context": "lyon-2",
		"determinant": "road traffic low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "casernedebonne_0trafic",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© AIA Life Designers-Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "social cohesion and involvement",
		"determinantFamilyLetter": "A",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_voteecole",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_habitatdiversifie",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_bibliotheque",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_enfantsvelos",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_assosbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_associationlaressource",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedrone",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "neighbourhood socio-economic status",
		"determinantFamilyLetter": "A",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_reunionbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "population economic activity and security",
		"determinantFamilyLetter": "A",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_mc2",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "population economic activity and security",
		"determinantFamilyLetter": "A",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedrone",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "active transportation choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_pietons",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "active transportation choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chronovelo",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_skatteurs",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_parkingveloeletrictrique",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_pistecyclacleverte",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_bifurk",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedronebarradis",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_potagercomposte",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_inaugbarradis",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "relaxing, cultural and recreational activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_espaceculturel",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "relaxing, cultural and recreational activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_bibliotheque",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_habitatdiversifie",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_habitatdiversifie",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_batimentdelabre",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "indoor air quality and hygrothermal comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_chantier",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_facadeensoleillees",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_facadesoleil",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_salleensoleillee",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "acoustic indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_nombreuxchantier",
		"priority": 0,
		"source": "",
		"title": "",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_pharmacie",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_basket",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chantierparticipatifbifurk",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chantier",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_confbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_potager",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedronedensite",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_batimentbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_siegeca",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "neighbourhood functional mix",
		"determinantFamilyLetter": "D",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_batimentbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "multi-sensory outdoor comfort and diversity",
		"determinantFamilyLetter": "E",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_barradis",
		"priority": 0,
		"source": "Ville de Grenoble\nService icono (Nathalie CAUVAT)",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "multi-sensory outdoor comfort and diversity",
		"determinantFamilyLetter": "E",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_coursdeaunature",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "aeraulic and hygrothermal outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_coursdeaunature",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "aeraulic and hygrothermal outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_affichecoursdeau",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "sun light exposure and visual outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_espaceexterieursoleil",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "interactions with natural environments",
		"determinantFamilyLetter": "E",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_planduparc",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS\n",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "urban appropriation access and equity",
		"determinantFamilyLetter": "F",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_banclabifurk",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "urban appropriation access and equity",
		"determinantFamilyLetter": "F",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_grafiti",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "spatial legibility and security feeling",
		"determinantFamilyLetter": "F",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vandalisme",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "spatial legibility and security feeling",
		"determinantFamilyLetter": "F",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vandalisme",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "spatial legibility and security feeling",
		"determinantFamilyLetter": "F",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_tagsurfacade",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS\n",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_marchabilite",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chronovelo",
		"priority": 0,
		"source": "Ville de Grenoble\nService icono (Nathalie CAUVAT)",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_velonature",
		"priority": 0,
		"source": "Ville de Grenoble\n Auriane Pouillet",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to and variety of the transportation offer",
		"determinantFamilyLetter": "G",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_intermodalites",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to and variety of the transportation offer",
		"determinantFamilyLetter": "G",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_lignedetram",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_jardinbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_coursdeaunature",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_affichescoursdeau",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chronovelo",
		"priority": 0,
		"source": "Ville de Grenoble\nService icono (Nathalie CAUVAT)",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "prevention and resilience to environmental hazards",
		"determinantFamilyLetter": "H",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_voieminerale",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity awareness",
		"determinantFamilyLetter": "H",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_potagerbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "air pollution and electromagnetic fields low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_pollutionvoiture",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "air pollution and electromagnetic fields low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_construction",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "air pollution and electromagnetic fields low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chantiers",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "qualitative and adequate sound environment",
		"determinantFamilyLetter": "I",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedronechantier",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "qualitative and adequate sound environment",
		"determinantFamilyLetter": "I",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_construction",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "qualitative and adequate sound environment",
		"determinantFamilyLetter": "I",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_chantiers",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "industrial, water and soil pollution low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_richardson",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "road traffic low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_trafficroutirt",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "social cohesion and involvement",
		"determinantFamilyLetter": "A",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_voteecole",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_habitatdiversifie",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_bibliotheque",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_enfantsvelos",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_assosbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_associationlaressource",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedrone",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "neighbourhood socio-economic status",
		"determinantFamilyLetter": "A",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_reunionbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "population economic activity and security",
		"determinantFamilyLetter": "A",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_mc2",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "population economic activity and security",
		"determinantFamilyLetter": "A",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedrone",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "active transportation choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_pietons",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "active transportation choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chronovelo",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_skatteurs",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_parkingveloeletrictrique",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_pistecyclacleverte",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_bifurk",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedronebarradis",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_potagercomposte",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_inaugbarradis",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "relaxing, cultural and recreational activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_espaceculturel",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "relaxing, cultural and recreational activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_bibliotheque",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_habitatdiversifie",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_habitatdiversifie",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_batimentdelabre",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "indoor air quality and hygrothermal comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_chantier",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_facadeensoleillees",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_facadesoleil",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_salleensoleillee",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "acoustic indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_nombreuxchantier",
		"priority": 0,
		"source": "",
		"title": "",
	},
	{
		"context": "la-saulaie",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_pharmacie",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_basket",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chantierparticipatifbifurk",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chantier",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_confbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_potager",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedronedensite",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_batimentbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_siegeca",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© AIA Life Designers",
	},
	{
		"context": "la-saulaie",
		"determinant": "neighbourhood functional mix",
		"determinantFamilyLetter": "D",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_batimentbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "multi-sensory outdoor comfort and diversity",
		"determinantFamilyLetter": "E",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_barradis",
		"priority": 0,
		"source": "Ville de Grenoble\nService icono (Nathalie CAUVAT)",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "multi-sensory outdoor comfort and diversity",
		"determinantFamilyLetter": "E",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_coursdeaunature",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "aeraulic and hygrothermal outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_coursdeaunature",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "aeraulic and hygrothermal outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_affichecoursdeau",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "sun light exposure and visual outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_espaceexterieursoleil",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "interactions with natural environments",
		"determinantFamilyLetter": "E",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_planduparc",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS\n",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "urban appropriation access and equity",
		"determinantFamilyLetter": "F",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_banclabifurk",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "urban appropriation access and equity",
		"determinantFamilyLetter": "F",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_grafiti",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "spatial legibility and security feeling",
		"determinantFamilyLetter": "F",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vandalisme",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "spatial legibility and security feeling",
		"determinantFamilyLetter": "F",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vandalisme",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "spatial legibility and security feeling",
		"determinantFamilyLetter": "F",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_tagsurfacade",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS\n",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_marchabilite",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chronovelo",
		"priority": 0,
		"source": "Ville de Grenoble\nService icono (Nathalie CAUVAT)",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_velonature",
		"priority": 0,
		"source": "Ville de Grenoble\n Auriane Pouillet",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "access to and variety of the transportation offer",
		"determinantFamilyLetter": "G",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_intermodalites",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "access to and variety of the transportation offer",
		"determinantFamilyLetter": "G",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_lignedetram",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_jardinbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_coursdeaunature",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_affichescoursdeau",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chronovelo",
		"priority": 0,
		"source": "Ville de Grenoble\nService icono (Nathalie CAUVAT)",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "prevention and resilience to environmental hazards",
		"determinantFamilyLetter": "H",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_voieminerale",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "environment and biodiversity awareness",
		"determinantFamilyLetter": "H",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_potagerbarradis",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "air pollution and electromagnetic fields low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_pollutionvoiture",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "air pollution and electromagnetic fields low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_construction",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "air pollution and electromagnetic fields low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "flaubert_chantiers",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "qualitative and adequate sound environment",
		"determinantFamilyLetter": "I",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_vuedronechantier",
		"priority": 0,
		"source": "Photo PressWeb - Ville de Grenoble",
		"title": "© Ville de Grenoble",
	},
	{
		"context": "la-saulaie",
		"determinant": "qualitative and adequate sound environment",
		"determinantFamilyLetter": "I",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_construction",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "qualitative and adequate sound environment",
		"determinantFamilyLetter": "I",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "flaubert_chantiers",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "la-saulaie",
		"determinant": "industrial, water and soil pollution low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "flaubert_richardson",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "la-saulaie",
		"determinant": "road traffic low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "flaubert_trafficroutirt",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "social cohesion and involvement",
		"determinantFamilyLetter": "A",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "jardinspartages_participationcitoyen",
		"priority": 0,
		"source": "Flickr",
		"title": "Jean-Sebastien Faure - ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "jardinspartages_participationcitoyen",
		"priority": 0,
		"source": "Flickr",
		"title": "Jean-Sebastien Faure - ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_ecoledarchi",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "social mixity, equity and solidarity",
		"determinantFamilyLetter": "A",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_mixiteintergenerationnelle",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "neighbourhood socio-economic status",
		"determinantFamilyLetter": "A",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_vueduquartier",
		"priority": 0,
		"source": "Flickr ",
		"title": "Thierry CHENU ©",
	},
	{
		"context": "villeurbanne",
		"determinant": "population economic activity and security",
		"determinantFamilyLetter": "A",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "jardinspartages_participationcitoyen",
		"priority": 0,
		"source": "Flickr",
		"title": "Jean-Sebastien Faure - ville de Grenoble",
	},
	{
		"context": "villeurbanne",
		"determinant": "active transportation choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "parc-jean-verlhac_espacevertspublic",
		"priority": 0,
		"source": "Flickr",
		"title": " Ville de Grenoble © 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "active transportation choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_escaliers",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© AIA Life Designers",
	},
	{
		"context": "villeurbanne",
		"determinant": "active transportation choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_cycliste",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2023 ",
	},
	{
		"context": "villeurbanne",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "parcjeanverlhac_accesactivitenautiques",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "ccas_stade",
		"priority": 0,
		"source": "Flickr",
		"title": "Thierry CHENU © 2021",
	},
	{
		"context": "villeurbanne",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "parc-jean-verlhac_parcetstades",
		"priority": 0,
		"source": "Flickr",
		"title": "Ville de Grenoble © 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "sport and physical activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_stadedefoot",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_marche",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_autrepointdevuedumarche",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_jardinpartage",
		"priority": 0,
		"source": "Flickr",
		"title": "FAURE Jean-Sebastien ",
	},
	{
		"context": "villeurbanne",
		"determinant": "healthy food knowledge and choice",
		"determinantFamilyLetter": "B",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_bar",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "relaxing, cultural and recreational activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "villeneuve_jardinpartage",
		"priority": 0,
		"source": "Flickr",
		"title": " © Jean Sébastien FAURE\nAout 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "relaxing, cultural and recreational activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "villeneuve_usagersdansjardinpartage",
		"priority": 0,
		"source": "Flickr",
		"title": "© Jean Sébastien FAURE\nAout 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "relaxing, cultural and recreational activities",
		"determinantFamilyLetter": "B",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "villeneuve_activitelac",
		"priority": 0,
		"source": "Ville de Grenoble",
		"title": "Auriane POILLET © Ville de Grenoble 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_vieuximmeuble",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_tourstaggees",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "stability and regularity of access to quality housing",
		"determinantFamilyLetter": "C",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_ecoquartierrenove",
		"priority": 0,
		"source": "Flickr",
		"title": "FAURE Jean-Sebastien",
	},
	{
		"context": "villeurbanne",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_vieuximmeuble",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "sun light access and visual indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "lavilleneuve_batimentsvuesurnature",
		"priority": 0,
		"source": "Flickr",
		"title": "Thierry CHENU ©",
	},
	{
		"context": "villeurbanne",
		"determinant": "acoustic indoor comfort",
		"determinantFamilyLetter": "C",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "villeneuve_parccalme",
		"priority": 0,
		"source": "Flickr",
		"title": "Ville de Grenoble © 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_panneauxespacesculturels",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to a diversified and qualitative offer",
		"determinantFamilyLetter": "D",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_marche",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_vuebatiments",
		"priority": 0,
		"source": "Ville de Grenoble\nService icono (Nathalie CAUVAT)",
		"title": "Natalie Cauvat",
	},
	{
		"context": "villeurbanne",
		"determinant": "urban concentration and urbanization level",
		"determinantFamilyLetter": "D",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_espaceurbain",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "neighbourhood functional mix",
		"determinantFamilyLetter": "D",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_vueduquartier",
		"priority": 0,
		"source": "Flickr",
		"title": "Thierry CHENU ©",
	},
	{
		"context": "villeurbanne",
		"determinant": "multi-sensory outdoor comfort and diversity",
		"determinantFamilyLetter": "E",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "parc-jean-verlhac_couverturevegetale",
		"priority": 0,
		"source": "Ville de Grenoble\nService icono (Nathalie CAUVAT)",
		"title": "Natalie Cauvat",
	},
	{
		"context": "villeurbanne",
		"determinant": "multi-sensory outdoor comfort and diversity",
		"determinantFamilyLetter": "E",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_toitsvegetaux",
		"priority": 0,
		"source": "Flickr",
		"title": "Thierry CHENU ©",
	},
	{
		"context": "villeurbanne",
		"determinant": "multi-sensory outdoor comfort and diversity",
		"determinantFamilyLetter": "E",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "parc-jean-verlhac_couverturevegetale",
		"priority": 0,
		"source": "Flickr",
		"title": "Ville de Grenoble © 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "aeraulic and hygrothermal outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_vueduquartier",
		"priority": 0,
		"source": "Flickr",
		"title": "Thierry CHENU ©",
	},
	{
		"context": "villeurbanne",
		"determinant": "sun light exposure and visual outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_toitsvegetaux",
		"priority": 0,
		"source": "Flickr",
		"title": "Thierry CHENU ©",
	},
	{
		"context": "villeurbanne",
		"determinant": "sun light exposure and visual outdoor comfort",
		"determinantFamilyLetter": "E",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_jardinpartageaoutbatiment",
		"priority": 0,
		"source": "Flickr",
		"title": "© Jean Sébastien FAURE",
	},
	{
		"context": "villeurbanne",
		"determinant": "interactions with natural environments",
		"determinantFamilyLetter": "E",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "parcjeanverlhac_accesactivitenautiques",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "urban appropriation access and equity",
		"determinantFamilyLetter": "F",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "jardinspartages_participationcitoyen",
		"priority": 0,
		"source": "Flickr",
		"title": "© Jean Sébastien FAURE\nAout 2022",
	},
	{
		"context": "villeurbanne",
		"determinant": "urban appropriation access and equity",
		"determinantFamilyLetter": "F",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_tourstaggees",
		"priority": 0,
		"source": "AIA LIFE DESIGNERS",
		"title": "AIA LIFE DESIGNERS",
	},
	{
		"context": "villeurbanne",
		"determinant": "spatial legibility and security feeling",
		"determinantFamilyLetter": "F",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_tagsurmur",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "road network quality for active transportation",
		"determinantFamilyLetter": "G",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_croisementroutetram",
		"priority": 0,
		"source": "© AIA Life Designers",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "access to and variety of the transportation offer",
		"determinantFamilyLetter": "G",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_trametvelo",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_espacesautourbatiments",
		"priority": 0,
		"source": "Ville de Grenoble\nService icono (Nathalie CAUVAT)",
		"title": "Nathalie CAUVAT",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_coursdeau",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2023 ",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_naturedanslequartier",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2023 ",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity preservation",
		"determinantFamilyLetter": "H",
		"determinantLetter": "1",
		"fileExtension": "jpg",
		"filename": "villeneuve_espacesverts",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2023 ",
	},
	{
		"context": "villeurbanne",
		"determinant": "prevention and resilience to environmental hazards",
		"determinantFamilyLetter": "H",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_solbetonne",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2023 ",
	},
	{
		"context": "villeurbanne",
		"determinant": "prevention and resilience to environmental hazards",
		"determinantFamilyLetter": "H",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_solbetonne1",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2023 ",
	},
	{
		"context": "villeurbanne",
		"determinant": "environment and biodiversity awareness",
		"determinantFamilyLetter": "H",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_coursdeau",
		"priority": 0,
		"source": "Flickr",
		"title": "Auriane POILLET © Ville de Grenoble 2023 ",
	},
	{
		"context": "villeurbanne",
		"determinant": "qualitative and adequate sound environment",
		"determinantFamilyLetter": "I",
		"determinantLetter": "2",
		"fileExtension": "jpg",
		"filename": "villeneuve_chantieramiente",
		"priority": 0,
		"source": "© AIA Life Designers-Jacques Merel",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "industrial, water and soil pollution low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_industriesetimeubles",
		"priority": 0,
		"source": "Flickr",
		"title": " Thierry CHENU ©",
	},
	{
		"context": "villeurbanne",
		"determinant": "industrial, water and soil pollution low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "3",
		"fileExtension": "jpg",
		"filename": "villeneuve_chantieramiente",
		"priority": 0,
		"source": "© AIA Life Designers ",
		"title": "© Jacques Merel",
	},
	{
		"context": "villeurbanne",
		"determinant": "road traffic low exposure",
		"determinantFamilyLetter": "I",
		"determinantLetter": "4",
		"fileExtension": "jpg",
		"filename": "villeneuve_traffic",
		"priority": 0,
		"source": "© AIA Life Designers ",
		"title": "© AIA Life Designers ",
	},
] as const;
